# Generated by Django 5.2.15 on 2026-06-18 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='bookings.province')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'province')},
            },
        ),
        migrations.CreateModel(
            name='TransportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('programme_activity', models.CharField(max_length=300)),
                ('date_of_request', models.DateField(auto_now_add=True)),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('destination', models.CharField(max_length=300)),
                ('num_vehicles', models.PositiveIntegerField(default=1)),
                ('num_drivers', models.PositiveIntegerField(default=1)),
                ('num_passengers', models.PositiveIntegerField(default=1)),
                ('is_emergency', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Submitted', max_length=20)),
                ('admin_comment', models.TextField(blank=True)),
                ('coordination_acknowledged', models.BooleanField(default=False)),
                ('coordination_note', models.TextField(blank=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transport_requests', to='bookings.department')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transport_requests', to='bookings.district')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transport_requests', to='bookings.province')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='fleet.driver')),
                ('transport_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='bookings.transportrequest')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='fleet.vehicle')),
            ],
        ),
    ]
