# Generated by Django 5.2.15 on 2026-06-23 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications_enabled', models.BooleanField(default=False)),
                ('notification_email', models.EmailField(blank=True, help_text='Recipient for new-request notifications. Required when email notifications are on.', max_length=254)),
                ('buffer_days', models.PositiveIntegerField(default=1, help_text='Minimum buffer days between consecutive trips for the same vehicle or driver.')),
                ('nudge_mode', models.CharField(choices=[('exact', 'Exact date overlap only'), ('7day', '7-day window around each trip'), ('custom', 'Custom ± days')], default='7day', help_text='Date window that triggers the coordination nudge when trips overlap.', max_length=10)),
                ('nudge_custom_days', models.PositiveIntegerField(default=7, help_text='Used only when nudge mode is "Custom ± days".')),
                ('default_maintenance_interval_km', models.PositiveIntegerField(default=5000, help_text='Default km interval between services applied to newly added vehicles.')),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
